### ISSUE TITLE
1.1.0 does not exist in Maven central

### ISSUE THREAD

**Issue by kiriakos** [dcdpr/libbech32-java#11]
Hi there, 

I wanted to use your lib and found that the `1.1.0` version advertised in the README.md is not available on any public maven registry I know. Maven central seems to only have `1.0.0`.

**Comment by danpape** [comment]
Thanks for the report. This may be an oversight on my part. I'll look into it and let you know.

**Comment by danpape** [comment]
Hey @kiriakos, after republishing the artifacts to maven central yesterday, they still didn't show up there correctly! Today I filed a ticket with the sonatype folks, and they claim they were having issues over there this weekend.

I think that as of right now, you should be able to build your project and your maven will retrieve the libbech32 1.1.0 artifacts from maven central...but if you go to the maven central website, you won't be able to find 1.1.0 there. Very weird--however, sonatype claims they will have that fixed in the next several hours or so.

Let me know if you have any other problems.

**Comment by danpape** [comment]
Seems like "search" is now up-to-date on the maven central site: https://search.maven.org/artifact/design.contract/libbech32
